---

- name: Fail on spaces in conf_d config names
  ansible.builtin.assert:
    that:
      - "' ' not in item.key"
  with_dict: "{{ nginx.conf_d }}"
  no_log: true

- name: Create nginx conf.d files
  when:
    - item.value is defined
    - item.value != None
    - item.value | length > 0
  with_dict: "{{ nginx.conf_d }}"
  ansible.builtin.template:
    src: nginx.conf_d.j2
    dest: "/etc/nginx/conf.d/{{ item.key }}.conf"
    mode: "0600"
    owner: root
    group: root
  no_log: true
  notify: (Re)start nginx service
